// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function App(Props) {
  var name = Props.name;
  return React.createElement("p", undefined, "Hello! " + name);
}

var make = App;

exports.make = make;
/* react Not a pure module */
